create table tb_schedule (id int8 generated by default as identity, description varchar(255), service varchar(255), type varchar(255), primary key (id));
INSERT INTO tb_schedule(type,description,service) VALUES ('Gato','Longo','Banho e Tosa');
